{% set name = "ngio" %}
{% set version = "0.5.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ngio-{{ version }}.tar.gz
  sha256: 58467668ea40e49dedbefc13eaf1b38c3d572befb0014f5d4aa7b3c432f3d685

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - filelock
    - zarr >3
    - anndata
    - pydantic
    - pandas >=1.2.0,<3.0.0
    - requests
    - aiohttp
    - dask <2025.11.0
    - distributed
    # - xarray
    - ome-zarr-models
    - pooch
    - polars
    - pyarrow
    - pillow

test:
  imports:
    - ngio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fractal-analytics-platform/ngio
  summary: Next Generation file format IO
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lorenzocerrone
    - jluethi
    - tcompa
