{% set name = "ngio" %}
{% set version = "0.3.5" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ngio-{{ version }}.tar.gz
  sha256: c3cf75d37beedff6b13b332e7a1514893de93421942d5cebc5dea8ad50c7cbe5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - anndata >=0.8.0
    - pydantic
    - pandas >=1.2.0
    - requests
    - aiohttp
    - zarr <3
    - dask
    - distributed
    - dask-image
    - pooch
    - filelock
    - xarray
    - ome-zarr-models
    - polars
    - pyarrow

test:
  imports:
    - ngio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fractal-analytics-platform/ngio
  summary: Next Generation file format IO
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lorenzocerrone
    - jluethi
    - tcompa
