{% set name = "ngio" %}
{% set version = "1.1.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/ngio-{{ version }}.tar.gz
  sha256: 4fd61ad2c6c949d8678b4ad932120f7370a18e6ea7a6bc885215a2bebdcaa531

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0
    - filelock >=3.12
    - zarr >=3.1.6
    - scipy >=1.14
    - fsspec >=2025.3
    - anndata >=0.12.5,<0.14.0
    - pydantic >=2.11.5
    - pandas >=2.2.2
    - aiohttp >=3.9
    - dask >=2024.1
    - distributed
    # - xarray  # still unused upstream
    - ome-zarr-models >=1.4
    - pooch >=1.8
    - polars >=1.0
    - pyarrow >=16
    - pillow >=10

test:
  imports:
    - ngio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fractal-analytics-platform/ngio
  summary: Next Generation file format IO
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lorenzocerrone
    - jluethi
    - tcompa
